services:
    web:
        build: .
        user: web-dev
        working_dir: /var/www/html
        ports:
            - "8088:8088"
        volumes:
            - .:/var/www/html
            - vendor:/var/www/html/vendor
        entrypoint: /var/www/html/run_dev_server.sh
    redis:
        image: redis/redis-stack:latest
        volumes:
            - ./_redis_data:/data
        ports:
            - "6379:6379"

volumes:
    vendor: